### ISSUE TITLE
How to update image of button 

### ISSUE THREAD

**Issue by realcarlos** [RafaelKayumov/RKTabView#18]
I use createButtonItemWithImage method to init a tabItem, and I want to change image of it when user click, is it possible?

**Comment by wongzigii** [comment]
I could  implement this as my own feature. But there is still no public interface, yet.

**Comment by wongzigii** [comment]
Any solution?

**Comment by RafaelKayumov** [comment]
@realcarlos, @wongzigii, now it's only possible to compose a new array of items which will include an item with updated image instead of item with old image. 
For example, you could store current array(mutable) of items in property. On button tap create new item with new image, replace old item from stored array with new item. Then set resulting array to tabView.
